spring:
  application:
    name: config-server-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\salas\IdeaProjects\cloud\config-server-service\src\main\resources\config

server:
  port: 8888
