spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    name: salas
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8081