spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    name: salas
    password: password


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true






#
#  spring.application.name=spring-demo-jpa
#
#  spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#  spring.datasource.name=salas
#  spring.datasource.password=password
#  #spring.jpa.hibernate.ddl-auto=create
#  spring.jpa.show-sql=true
#  spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
